config/routes.rb
FbTest::Application.routes.draw do
  resources :stories

  get "static_pages/facebook"
  get "static_pages/beacon"
  get "static_pages/index"
  
  
  resources :tests
  root 'static_pages#home'

  

end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def beacon
  end
  
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to stories_url }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :content, :origin, :destination, :orLat, :orLng, :desLat, :desLng, :photo)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test }
      else
        format.html { render action: 'new' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params[:test]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
body{
	padding-top:50px !important;
	background-color: white !important;
}  

nav{
background:white;
position:fixed;
left:0;
top:0;
z-index:10;
width:100%;
background-color:#dd4814;
color:white;
}

nav ul{
overflow:auto;
list-style:none;
margin:0;
}

nav li{
float:left;
}

nav a{
color:white;
display:block;
padding:20px;
text-decoration:none;
font-weight:bold;
font-family: helvetica;
font-size: 17px;
font-weight: bold;

}

nav a:hover{
background:#253652;
color:white;
}

a{
color:#253652;
font-family:verdana;
text-decoration:none;
font-weight:bold;
}

.container h2
{
	color:white;
}

.container p
{
	color:white;
}

#conversation_holder,#conversation_div{
	background-color: #F7F7F7;
}
    </style>
  <title>Twin Cities</title>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/bootswatch/3.0.0/simplex/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</head>
<body>
	<nav>
      <ul class="pull-left">
        <li><a href="#" onClick="jarallax.jumpToProgress( 0, 2000, 30);">Intro</a></li>
        <li><a href="#" onClick="jarallax.jumpToProgress( 10, 2000, 30);">What is MindFire?</a></li>
        <li><a href="#" onClick="jarallax.jumpToProgress( 20, 2000, 30);">About Us</a></li>
      </ul>
		
      <form accept-charset="UTF-8" action="#" class="navbar-form pull-right" method="post">
        <div id="fb-root"></div>
	
		<fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button>
		<span onclick="logout()"> Logout </span>
      </form>
    </nav>
<div class="container">
	<%= yield %>
</div>
	<!--
	<div id="friends_list">
	</div>
	-->
	

</body>
</html>

app/views/static_pages/beacon.html.erb
	<div class="row">
        <div class="col-sm-12">
        	Create your beacon <br />
         	Name <input type="text" id="name" /> <br />
			Description <input type="text" id="description" />
        </div><!-- /.col-sm-4 -->
    </div>
	

app/views/static_pages/facebook.html.erb
<style>
html, body, #map-canvas {
    height: 800px;
    margin: 0px;
    padding: 0px
}
</style>

<div class="row">
	<div class="col-sm-12">
    	<%= link_to("Beacon", static_pages_beacon_path) %>
    	
   </div>
   <div class="col-sm-12">
    <div>
    	<button type="button" style="display:none" id="conversation_toggler" class="btn btn-danger" data-toggle="collapse" data-target="#conversation_div">
		  simple collapsible
		</button>

		<div id="conversation_div" class="collapse out panel">
			Tons of awesome conversations
			<span style="float:right;cursor:pointer;" onclick="$('#conversation_div').collapse('hide');"><span class="glyphicon glyphicon-chevron-down"></span>&nbsp;Hide conversation &nbsp;</span>
			<input type="text" id="message_area" class="form-control" placeholder="Say Something!!!">
			<div id="conversation_holder" />
			</div>
		</div>
    	<div id="map-canvas"></div>
    </div>
    
    <div id="chat"></div>
    </div><!-- /.col-sm-4 -->
</div>
 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
        	<h4>LOG IN!!!</h4>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
	

app/views/static_pages/home.html.erb
<style>

.graticule {
  fill: none;
  stroke: #777;
  stroke-opacity: .5;
  stroke-width: .5px;
}

.land {
  fill: #222;
}

.boundary {
  fill: none;
  stroke: #fff;
  stroke-width: .5px;
}

</style>

<div class="row">
	<div class="col-md-12" id="canvas" style="text-align:center;"> 
	</div>
</div>

<script src="http://d3js.org/topojson.v0.min.js"></script>
<script>
//http://www.d3noob.org/2013/03/a-simple-d3js-map-explained.html
var width = 960,
    height = 500;

var projection = d3.geo.mercator()
    .center([0, 5 ])
    .scale(120)
    .rotate([-180,0]);

var svg = d3.select("#canvas").append("svg")
    .attr("width", width)
    .attr("height", height);

var path = d3.geo.path()
    .projection(projection);

var g = svg.append("g");
// load and display the World
d3.json("assets/world-110m2.json", function(error, topology) {
    g.selectAll("path")
      .data(topojson.object(topology, topology.objects.countries)
          .geometries)
    .enter()
      .append("path")
      .attr("d", path)
      
    //add circles
    d3.json("assets/test.json", function(error, data) {
    	console.log(data);
    	//console.log(data.points[0].latitude);
        g.selectAll("circle")
           .data(data.points)
           .enter()
           .append("circle")
           .attr("cx", function(d) {
           		console.log(d);
                return projection([d.longitude, d.latitude])[0];
           })
           .attr("cy", function(d) {
           		return projection([d.longitude, d.latitude])[1];
           })
           .attr("r", 5)
           .style("fill", "red");  
	});
	
	d3.svg.line()
	.x(function(d) { return projection(100, 100); })
    .y(function(d) { return projection(100, 100); })
    .interpolate("basis");
      
});


// zoom and pan
var zoom = d3.behavior.zoom()
    .on("zoom",function() {
        g.attr("transform","translate("+ 
            d3.event.translate.join(",")+")scale("+d3.event.scale+")");
        g.selectAll("path")  
            .attr("d", path.projection(projection)); 
  });

svg.call(zoom)
</script>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
      <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      var jarallax
      init = function() {
        jarallax = new Jarallax(new ControllerScroll(true));
        var currentProgress = 0;
        var progressSteps = 1 / 3;
        
        jarallax.setDefault('.container',{opacity:0, display:'none'})
        
        jarallax.addAnimation('.logo',[{progress:'0', opacity:'1', backgroundPositionY:'50%'},
                                       {progress:'10', opacity:'0', backgroundPositionY:'0%'},
                                       {progress:'100%', opacity:'0', backgroundPositionY:'0%'}]);
                                       
        var animation = jarallax.addAnimation('#slide1',[{progress:'0', display:'block', opacity:'0', top:'100%'},
                                                         {progress:'10', display:'block', opacity:'1', top:'20%'},
                                                         {progress:'20', display:'block', opacity:'0', top:'20%'}]);
                                                         
        jarallax.cloneAnimation('#slide2',{progress:'+10'}, animation);
      }
    </script>
    <style>
    	body{
display:block;
padding:0;
margin:0;
height:1500px;
background-image:url(../image/bg.jpg);
}

h1, .logo{
margin:0;
padding:0;
position:fixed;
z-index:2;
width:100%;
font-family:verdana;
}

h2{
top:40%;
color:black;
font-size: 40px;
}

.container{
opacity:0;
margin:0 auto;
padding: 0 100px;
overflow:hidden;
height:100%;
position:fixed;
z-index:2;
font-family:verdana;
}

.logo{
display:block;
text-indent:10000px;
overflow:hidden;
background: white url(../image/logo.png) center center no-repeat;
background-position-y:50%;
height:100%;
width:100%;
}

nav{
background:white;
border-bottom:2px solid black;
position:fixed;
left:0;
top:0;
z-index:10;
width:100%;
}

nav ul{
overflow:auto;
list-style:none;
margin:0;
}

nav li{
float:left;
}

nav a{
color:#253652;
font-family:verdana;
display:block;
padding:20px;
text-decoration:none;
font-weight:bold;
}

nav a:hover{
background:#253652;
color:white;
}

a{
color:#253652;
font-family:verdana;
text-decoration:none;
font-weight:bold;
}

.container h2
{
	color:white;
}

.container p
{
	color:white;
}
    </style>
  </head>
  <body onLoad='init()'>
    <nav>
      <ul class="pull-left">
        <li><a href="#" onClick="jarallax.jumpToProgress( 0, 2000, 30);">Intro</a></li>
        <li><a href="#" onClick="jarallax.jumpToProgress( 10, 2000, 30);">What is MindFire?</a></li>
        <li><a href="#" onClick="jarallax.jumpToProgress( 20, 2000, 30);">About Us</a></li>
      </ul>

      <form accept-charset="UTF-8" action="#" class="navbar-form pull-right" method="post">
          <div id="fb-root"></div>
	
		<fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button>
		<button onclick="logout()"> Logout </button>
      </form>
    </nav>
    <h1 class="logo">Jarallax</h1>
    <div class="container" id="slide1">
      <h2>What is MindFire?</h2>
      <p>
        <b>It is this...</b>
      </p>
    </div>
    <div class="container" id="slide2">
      <h2>About Us</h2>
      <p>
        Here we add some crap abouy ourselves. Doesn't need to be the truth. :P Who cares, right? Muhahaha. But we should have something fancy.
      </p>
    </div>
  </body>
</html>

app/views/static_pages/maps.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
<title>Simple markers</title>
<style>
html, body, #map-canvas {
    height: 100%;
    margin: 0px;
    padding: 0px
}

</style>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
function initialize() {
    var myLatlng = new google.maps.LatLng(-28.363882,-131.044922);
    var mapOptions = {
zoom: 4,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var sampleLatLong = [['7.86031877', '39.81935319'], ['1.84691275', '-111.58996009'], ['34.01257398', '1.72659234'], ['-17.47547016', '19.77515979'], ['1.71210013', '-177.11291204'], ['41.15213121', '-168.85202595'], ['21.83475018', '-33.26717111'], ['-29.12041748', '-10.17708521'], ['2.47133637', '94.01706029'], ['44.48996264', '143.03173651'], ['-31.89397752', '149.46615871'], ['-28.13054545', '-61.86803933'], ['1.42537381', '-26.34834498'], ['31.27927883', '8.39556014'], ['54.31577821', '-45.17456093'], ['-40.31520315', '-52.63845233'], ['33.04040823', '-7.51488665'], ['5.33293845', '34.06620763'], ['-54.38479821', '-118.43043001'], ['11.05580157', '67.9898784'], ['-11.27375041', '-139.8567679'], ['25.00177535', '-4.76708371'], ['27.66895395', '-121.73285183'], ['16.63907493', '144.2856704'], ['-6.08672441', '15.37433306'], ['81.85738421', '44.18278053'], ['20.20447124', '153.41103279'], ['39.02828897', '-77.85237679'], ['61.64257024', '-123.38839279'], ['-19.54002706', '-41.59497941'], ['-29.7165399', '-44.72256881'], ['83.80253622', '90.33442947'], ['-41.15200361', '-150.42450076'], ['-28.75877311', '150.4196504'], ['-43.02110989', '-113.45195026'], ['45.38155483', '-139.22981394'], ['-9.83815991', '157.57505466'], ['25.93703332', '160.80884563'], ['30.25852148', '96.64232383'], ['-19.65667665', '100.73916625'], ['15.72410221', '167.09779956'], ['15.48976024', '-79.01729881'], ['33.88808244', '-67.43074528'], ['1.17665824', '118.60663338'], ['23.48700035', '70.17714844'], ['-11.19088562', '-101.55920489'], ['-32.81127593', '103.89076905'], ['-32.20454149', '51.49978059'], ['41.24425886', '33.92370396'], ['13.89583956', '-147.16387974']]

        var marker = new google.maps.Marker({
animation:google.maps.Animation.BOUNCE,
position: myLatlng,
map: map,
title: '',
icon: 'icons/fire.png',
});

var LatLngArray  = new Array(sampleLatLong.length);

for (var i=0; i < sampleLatLong.length ; i++)
{
    LatLngArray[i] = new google.maps.LatLng(sampleLatLong[i][0],sampleLatLong[i][1]);

    var marker = new google.maps.Marker({
position: LatLngArray[i],
animation:google.maps.Animation.BOUNCE,
map: map,
title: '',
icon: 'icons/fire.png',
});

}
}

google.maps.event.addDomListener(window, 'load', initialize);

</script>
</head>
<body>
<div id="map-canvas"></div>
</body>
</html>

app/views/static_pages/maps2.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
<title>Simple markers</title>
<style>
html, body, #map-canvas {
    height: 100%;
    margin: 0px;
    padding: 0px
}

</style>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
function initialize() {
    var myLatlng = new google.maps.LatLng(-28.363882,-131.044922);
    var mapOptions = {
zoom: 4,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var sampleLatLong = [['7.86031877', '39.81935319'], ['1.84691275', '-111.58996009'], ['34.01257398', '1.72659234'], ['-17.47547016', '19.77515979'], ['1.71210013', '-177.11291204'], ['41.15213121', '-168.85202595'], ['21.83475018', '-33.26717111'], ['-29.12041748', '-10.17708521'], ['2.47133637', '94.01706029'], ['44.48996264', '143.03173651'], ['-31.89397752', '149.46615871'], ['-28.13054545', '-61.86803933'], ['1.42537381', '-26.34834498'], ['31.27927883', '8.39556014'], ['54.31577821', '-45.17456093'], ['-40.31520315', '-52.63845233'], ['33.04040823', '-7.51488665'], ['5.33293845', '34.06620763'], ['-54.38479821', '-118.43043001'], ['11.05580157', '67.9898784'], ['-11.27375041', '-139.8567679'], ['25.00177535', '-4.76708371'], ['27.66895395', '-121.73285183'], ['16.63907493', '144.2856704'], ['-6.08672441', '15.37433306'], ['81.85738421', '44.18278053'], ['20.20447124', '153.41103279'], ['39.02828897', '-77.85237679'], ['61.64257024', '-123.38839279'], ['-19.54002706', '-41.59497941'], ['-29.7165399', '-44.72256881'], ['83.80253622', '90.33442947'], ['-41.15200361', '-150.42450076'], ['-28.75877311', '150.4196504'], ['-43.02110989', '-113.45195026'], ['45.38155483', '-139.22981394'], ['-9.83815991', '157.57505466'], ['25.93703332', '160.80884563'], ['30.25852148', '96.64232383'], ['-19.65667665', '100.73916625'], ['15.72410221', '167.09779956'], ['15.48976024', '-79.01729881'], ['33.88808244', '-67.43074528'], ['1.17665824', '118.60663338'], ['23.48700035', '70.17714844'], ['-11.19088562', '-101.55920489'], ['-32.81127593', '103.89076905'], ['-32.20454149', '51.49978059'], ['41.24425886', '33.92370396'], ['13.89583956', '-147.16387974']]


    var marker = new google.maps.Marker({
        animation:google.maps.Animation.BOUNCE,
        position: myLatlng,
        map: map,
        title: '',
        icon: 'icons/fire.png',
        });


var LatLngArray  = new Array(sampleLatLong.length);
   var infowindow = new google.maps.InfoWindow();
var i;
for (i=0; i < sampleLatLong.length ; i++)
{
    LatLngArray[i] = new google.maps.LatLng(sampleLatLong[i][0],sampleLatLong[i][1]);

var content = '<div class="map-content"><h3>' + i;
        var marker = new google.maps.Marker({
            map: map,
            title: "",
            position: new google.maps.LatLng(sampleLatLong[i][0],sampleLatLong[i][1]),
icon: 'icons/fire.png',
animation:google.maps.Animation.BOUNCE,
        });
        google.maps.event.addListener(marker, 'click', (function(marker, content) {
            return function() {
                infowindow.setContent(content);
                infowindow.open(map, marker);
            }
        })(marker, content));

        
        }
}
        
        google.maps.event.addDomListener(window, 'load', initialize);


</script>
</head>
<body>
<div id="map-canvas"></div>
</body>
</html>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<style>
	.item {
  margin-bottom: 10px;
}
</style>
<div class="row">
	<div class="col-md-7">
		<h1>Twin Cities</h1>
	</div>
	<div class="col-md-5">
		<p>
		<%= link_to "http://localhost:3000" do %>
			Visualize the problem
		<% end %>
		<%= link_to new_story_path do %>
			Register a new story
		<% end %>
		</p>
	</div>
</div>
</div>
<div style="width: 100%;">
		<div id="container" class="js-masonry" data-masonry-options='{  "itemSelector": ".item", "gutter": 10, "isFitWidth": true }'>
			<% @stories.each do |story| %>
			  <div class="item">
			  	<img src="<%= story.photo %>" /> 
			  </div>
			<% end %>
		</div>
</div>
<div style="display:none;">
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Orlat</th>
      <th>Orlng</th>
      <th>Deslat</th>
      <th>Deslng</th>
      <th>sss</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.name %></td>
        <td><%= story.content %></td>
        <td><%= story.origin %></td>
        <td><%= story.destination %></td>
        <td><%= story.orLat %></td>
        <td><%= story.orLng %></td>
        <td><%= story.desLat %></td>
        <td><%= story.desLng %></td>
        <td><%= story.photo %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>
</div>

app/views/stories/new.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=places&types=geocode&key=AIzaSyAixPSdrVVM3DwcWdaHix1_WiXLRok7F28"></script>
 <script>
function initialize() {
 
  var input = /** @type {HTMLInputElement} */(document.getElementById('q'));
  var options = { componentRestrictions: {} };
  var autocomplete = new google.maps.places.Autocomplete(input,options);
  var input2 = /** @type {HTMLInputElement} */(document.getElementById('q2'));
  var autocomplete2 = new google.maps.places.Autocomplete(input2,options);
  autocomplete.setTypes(['geocode']);

  var infowindow = new google.maps.InfoWindow();

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    //input.className = '';
    
    $("#lat1").val(autocomplete.getPlace().geometry.location.lng());
    $("#lng1").val(autocomplete.getPlace().geometry.location.lat());
    //$("#buscador").submit(); //line that submits
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
   
    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    //infowindow.open(map, marker);
  });
 
	google.maps.event.addListener(autocomplete2, 'place_changed', function() {
    infowindow.close();
    //input.className = '';
    
    $("#lat2").val(autocomplete.getPlace().geometry.location.lng());
    $("#lng2").val(autocomplete.getPlace().geometry.location.lat());
    //$("#buscador").submit(); //line that submits
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input2.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
   
    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    //infowindow.open(map, marker);
  }); 
 
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @story.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @story.content %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @story.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @story.destination %>
</p>

<p>
  <strong>Orlat:</strong>
  <%= @story.orLat %>
</p>

<p>
  <strong>Orlng:</strong>
  <%= @story.orLng %>
</p>

<p>
  <strong>Deslat:</strong>
  <%= @story.desLat %>
</p>

<p>
  <strong>Deslng:</strong>
  <%= @story.desLng %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>